/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import javax.swing.JTextField;
import java.awt.event.ActionListener;
import javax.swing.JButton;
import javax.swing.JPasswordField;
/**
 *
 * @author Mirah
 */
public class Registrasi extends javax.swing.JPanel {

    /**
     * Creates new form Registrasi
     */
    public Registrasi() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tfnama = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        tfusername = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        tfpassword = new javax.swing.JPasswordField();
        jLabel5 = new javax.swing.JLabel();
        tfulangipassword = new javax.swing.JPasswordField();
        bottonkembaliregistrasi = new javax.swing.JButton();
        bottonregistrasiregistrasi = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("REGISTRASI");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel2.setText("Nama");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel3.setText("Username");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel4.setText("Password");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel5.setText("Ulangi Password");

        bottonkembaliregistrasi.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        bottonkembaliregistrasi.setText("Kembali");

        bottonregistrasiregistrasi.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        bottonregistrasiregistrasi.setText("Registrasi");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(162, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(142, 142, 142))
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(bottonkembaliregistrasi)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 165, Short.MAX_VALUE)
                        .addComponent(bottonregistrasiregistrasi))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel4)
                                .addComponent(jLabel3)))
                        .addGap(50, 50, 50)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tfusername)
                            .addComponent(tfnama)
                            .addComponent(tfpassword)
                            .addComponent(tfulangipassword, javax.swing.GroupLayout.DEFAULT_SIZE, 187, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(113, 113, 113))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(tfnama, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfusername, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfpassword, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(23, 23, 23)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(tfulangipassword, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bottonkembaliregistrasi)
                    .addComponent(bottonregistrasiregistrasi))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    public String getNama(){
        return tfnama.getText();
    }
    public String getUsername(){
        return tfusername.getText();
    }
    public char[] getPassword(){
        return tfpassword.getPassword();
    }
    public char[] getUlangiPassword(){
        return tfulangipassword.getPassword();
    }
    public JTextField getTfNama(){
        return tfnama;
    }
    public JTextField getTfUsername(){
        return tfusername;
    }
    public JPasswordField getTfPassword(){
        return tfpassword;
    }
    public JPasswordField getTfUlangiPassword(){
        return tfulangipassword;
    }
    public void setNama(String nama){
        tfnama.setText(nama);
    }
    public void setUsername(String username){
        tfusername.setText(username);
    }
    public void setPassword(String password){
        tfpassword.setText(password);
    }
    public void setUlangiPassword(String ulangipassword){
        tfulangipassword.setText(ulangipassword);
    }
    public JButton getBtnKembaliRegistrasi(){
        return bottonkembaliregistrasi;
    }
    public JButton getBtnRegistrasiRegistrasi(){
        return bottonregistrasiregistrasi;
    }
    public void addListener(ActionListener ae){
        bottonkembaliregistrasi.addActionListener(ae);
        bottonregistrasiregistrasi.addActionListener(ae);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bottonkembaliregistrasi;
    private javax.swing.JButton bottonregistrasiregistrasi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField tfnama;
    private javax.swing.JPasswordField tfpassword;
    private javax.swing.JPasswordField tfulangipassword;
    private javax.swing.JTextField tfusername;
    // End of variables declaration//GEN-END:variables
}
